services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: odoo_sync
      POSTGRES_PASSWORD: odoo_sync
      POSTGRES_DB: odoo_sync
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://odoo_sync:odoo_sync@db:5432/odoo_sync
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app

volumes:
  pgdata:
